import "server-only";
import { prisma } from "@/lib/db/prisma";
import { buildTasteSignal } from "@/lib/recommendations/signals";
import { movieToCard, showToCard } from "@/lib/content/mappers";
import { parsePrompt } from "@/lib/ai/prompt-parser";
import type { ContentCard } from "@/types/content";

export interface GeneratedItem {
  card: ContentCard;
  reason: string;
}

export interface GeneratedWatchlist {
  title: string;
  description: string;
  matchedMoods: string[];
  matchedGenres: string[];
  items: GeneratedItem[];
}

const GENRE_INCLUDE = { genres: true } as const;

function titleCase(words: string[]): string {
  return words.map((w) => w[0].toUpperCase() + w.slice(1)).join(", ");
}

/**
 * Turns a natural-language request into a real, personalized watchlist.
 * There's no LLM in this environment — the prompt is parsed against Aurora's
 * actual mood/genre vocabulary (parsePrompt), candidates come straight from
 * the catalog, and every per-item reason names the specific mood/genre match
 * or taste-signal weight that got it picked. Nothing is generated by a
 * model; it's a transparent, rule-based ranking over real data.
 */
export async function generateWatchlist(userId: string, prompt: string): Promise<GeneratedWatchlist> {
  const [intent, signal] = await Promise.all([parsePrompt(prompt), buildTasteSignal(userId)]);

  const includeMovies = intent.kindHint !== "tv_show" && intent.kindHint !== "music";
  const includeShows = intent.kindHint !== "movie" && intent.kindHint !== "music";

  const moodFilter = intent.moods.length > 0 ? { moods: { hasSome: intent.moods } } : {};
  const genreFilter = intent.genres.length > 0 ? { genres: { some: { name: { in: intent.genres } } } } : {};

  const [movies, shows] = await Promise.all([
    includeMovies
      ? prisma.movie.findMany({
          where: {
            ...moodFilter,
            ...genreFilter,
            id: { notIn: [...signal.seen.movieIds] },
            ...(intent.excludedGenres.length > 0 ? { genres: { none: { name: { in: intent.excludedGenres } } } } : {}),
          },
          include: GENRE_INCLUDE,
          take: 60,
          orderBy: { communityRating: "desc" },
        })
      : [],
    includeShows
      ? prisma.tVShow.findMany({
          where: {
            ...moodFilter,
            ...genreFilter,
            id: { notIn: [...signal.seen.showIds] },
            ...(intent.excludedGenres.length > 0 ? { genres: { none: { name: { in: intent.excludedGenres } } } } : {}),
          },
          include: GENRE_INCLUDE,
          take: 60,
          orderBy: { communityRating: "desc" },
        })
      : [],
  ]);

  const candidates: ContentCard[] = [...movies.map(movieToCard), ...shows.map(showToCard)].filter(
    (c) => !c.moods?.some((m) => intent.excludedMoods.includes(m))
  );

  const scored = candidates.map((card) => {
    const moodMatch = (card.moods ?? []).filter((m) => intent.moods.includes(m)).length;
    const genreMatch = (card.genres ?? []).filter((g) => intent.genres.includes(g)).length;
    const tasteScore =
      (card.genres ?? []).reduce((sum, g) => sum + Math.max(0, signal.genreWeights.get(g) ?? 0), 0) +
      (card.moods ?? []).reduce((sum, m) => sum + Math.max(0, signal.moodWeights.get(m) ?? 0), 0) * 0.6;
    const promptMatch = moodMatch * 3 + genreMatch * 2;
    return { card, promptMatch, tasteScore, score: promptMatch * 10 + tasteScore + (card.rating ?? 0) * 0.3 };
  });

  scored.sort((a, b) => b.score - a.score);
  const top = scored.slice(0, intent.count);

  const items: GeneratedItem[] = top.map(({ card, promptMatch, tasteScore }) => {
    const matchedMood = (card.moods ?? []).find((m) => intent.moods.includes(m));
    const matchedGenre = (card.genres ?? []).find((g) => intent.genres.includes(g));
    let reason: string;
    if (promptMatch > 0) {
      const parts = [matchedGenre, matchedMood].filter(Boolean);
      reason = `${parts.join(", ")} — matches what you asked for.`;
    } else if (tasteScore > 0) {
      const topGenre = (card.genres ?? []).sort(
        (a, b) => (signal.genreWeights.get(b) ?? 0) - (signal.genreWeights.get(a) ?? 0)
      )[0];
      reason = topGenre ? `You often enjoy ${topGenre.toLowerCase()}.` : "Matches your usual taste.";
    } else {
      reason = "Highly rated by the Aurora community.";
    }
    return { card, reason };
  });

  const titleParts = [...intent.moods.slice(0, 2), ...intent.genres.slice(0, 1)];
  const title = titleParts.length > 0 ? `${titleCase(titleParts)} Watchlist` : "Your AI Watchlist";

  return {
    title,
    description: prompt.trim(),
    matchedMoods: intent.moods,
    matchedGenres: intent.genres,
    items,
  };
}
